### ISSUE TITLE
Marker spec height issue on a custom icon marker

### ISSUE THREAD

**Issue by kheldiente** [Appolica/InteractiveInfoWindowAndroid#1]
Hi, I have an issue in regards to setting marker spec height on a custom icon marker.  Values i use is 20 for the width and 170 on height. It's not setting though to a specif height i want. Testing it on asus zenfone 2 5.5 laser and samsung edge. Please see screenshot. Both runs in marshmallow

Samsung - where  i want to set the window
![samsung_marker_spec_height_issue](https://cloud.githubusercontent.com/assets/11827362/19178252/97d7a142-8c83-11e6-8add-6f76fde05ba8.png)

Asus screenshot - wrong
![asus_marker_spec_height_issue](https://cloud.githubusercontent.com/assets/11827362/19178241/7f7df2d6-8c83-11e6-9a82-c2840d08ed48.jpg)

Appreciate your help. Thanks!

**Comment by bkolarov-appolica** [comment]
Hi,
Thanks for using our lib! 
Are you setting these values directly through code, without any conversion? You shoud use dp values, not exact numbers. 

The marker dimensions are used as an offset. If you pass the exact height of the marker, the InfoWindow will be placed right above it. (I thought it will be good if I mention that)

Please let me know if the problem was not using dp or something else.
Good luck!

**Comment by kheldiente** [comment]
Hi, I was indeed setting the values through code. My bad. Getting the dp
values of the drawble did it. Thanks a lot. Kudos!

**Comment by bkolarov-appolica** [comment]
Glad we helped.
