### ISSUE TITLE
Use this library inside a fragment

### ISSUE THREAD

**Issue by MahmoudiOussama** [Appolica/InteractiveInfoWindowAndroid#26]
Hi Appolica team, this is a great library, great work for sure.

Can you please provide a sample which uses this library inside a fragment ? not inside an activity.

And thank you.

**Comment by kkaun** [comment]
Same kind request here. For sure that's a classy library but I can't make it for Fragments. 
Although I've already implemented InfoWindowManager inside my custom Fragment's lifecycle and logged almost 90% of it's inner methods, InfoWindow still remains hidden on click of the marker and I can't figure out why, mainly because of kinda verbose lib code remaining to understand.
Adding simple example for Fragment with MapView inside wrapped by your TouchInterceptFrameLayout would be so cool.

**Comment by jayjhaveri** [comment]
> Hi Appolica team, this is a great library, great work for sure.
> 
> Can you please provide a sample which uses this library inside a fragment ? not inside an activity.
> 
> And thank you.

Hi,
What is the issue you are facing?

**Comment by MahmoudiOussama** [comment]
Hi [jayjhaveri](https://github.com/jayjhaveri), thank you for your response even thought it is a <b>little bit late</b> (more than a year).
So, from what i remember, i was trying to use your library inside my android project. The project contains one single Activity and about 15 Fragments, one of those fragments contains a google map, and i wanted to use your library inside the google map fragment, but i couldn't achieve it.
Sorry, i couldn't remember what was the error, or what is written in the logs back then.

**Comment by sarbogast** [comment]
I'm having the same issue. Unfortunately, even the official documentation for the Google Maps SDK doesn't seem to show any example on how to integrate vanilla Google Maps into a fragment. So I think I found the following setup on a StackOverflow answer somewhere and it works:

Fragment layout XML file:
```
<LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent" xmlns:app="http://schemas.android.com/apk/res-auto"
        tools:context=".ToolListFragment"
        android:orientation="vertical"
        android:background="@android:color/white">
...
   <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/map_container">
        <!-- The map fragments will go here -->
    </RelativeLayout>
...
</LinearLayout>
```

Then in the Fragment class file (Kotlin):
```
class ToolListFragment : Fragment(R.layout.fragment_tool_list),
    OnMapReadyCallback {
    
    private lateinit var mapFragment: SupportMapFragment

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)

        val fragment = childFragmentManager.findFragmentById(R.id.map_container)
        if (fragment == null) {
            mapFragment = SupportMapFragment.newInstance()
            childFragmentManager.beginTransaction().replace(R.id.map_container, mapFragment)
                .commit()
        } else {
            mapFragment = fragment as SupportMapFragment
        }

        mapFragment.getMapAsync(this)
    }
...
}
```

I don't understand everything about this setup but it works.
Now I would like to replace the vanilla `SupportMapFragment` by your `MapInfoWindowFragment`, but I don't know how to instantiate it properly in `onActivityCreated`. And if I add it to the layout file directly as in your example, I can't figure out how to retrieve a reference to it in `onActivityCreated` in order to call `getMapAsync` on it. 

Any idea?

**Comment by dpetrov-appolica** [comment]
Example with Fragment is added.
